<?php
/**
 * SkuRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * SkuRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SkuRequest
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SkuRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SkuRequest"
     */
    public function testSkuRequest()
    {
    }

    /**
     * Test attribute "stock_id"
     */
    public function testPropertyStockId()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "code_type"
     */
    public function testPropertyCodeType()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "custom_order_reference"
     */
    public function testPropertyCustomOrderReference()
    {
    }

    /**
     * Test attribute "quantity_handled"
     */
    public function testPropertyQuantityHandled()
    {
    }

    /**
     * Test attribute "request_handled"
     */
    public function testPropertyRequestHandled()
    {
    }

    /**
     * Test attribute "quantity_needed"
     */
    public function testPropertyQuantityNeeded()
    {
    }
}
